[package]
name = "findfox"
version = "0.1.0"
authors = ["build"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "0.9.0"
